stages:
    - coveragetest

test:
    stage: coveragetest
    image: golang
    script:
        - go get github.com/t-yuki/gocover-cobertura
        - go test  ./... -v -coverprofile coverage.txt
        - gocover-cobertura < coverage.txt > coverage.xml
    coverage: /^coverage:\s(\d+(?:\.\d+)?%)/
    artifacts:
      name: $CI_JOB_NAME/coverage.txt
      paths:
        - coverage.xml
      expire_in: 2 days
      reports:
        cobertura: coverage.xml